version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          - RAILS_ENV: 'test'
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          - MYSQL_ROOT_HOST: '%'

    working_directory: ~/project

    steps:
      - checkout
      - run: bundle install
      - run: mv config/database.yml.ci config/database.yml
      - run: bundle exec rails db:create db:migrate RAILS_ENV=test
      - run: bundle exec rails test
